### ISSUE TITLE
gitee图床配置报错 说not fund project

### ISSUE THREAD

**Issue by zhaoshuailongLxw** [MartyAlien/plugin-giteeoss#3]
强烈建议出一篇gitee 配置教程，您那个动态图那个都填写 对新手不太友好，目前好多都是集成各种云oss，gitee太少了，希望作者出一篇博客gitee配置halo博客教程（尤其是halo配置gitee那些要填写什么） 谢谢

**Comment by MartyAlien** [comment]
你好，我收到了你的反馈，这个问题也是插件出来的时候我也发现了，资源未被找到的原因是因为Gitee官方的防盗链机制识别了请求资源的Refer信息，导致图片资源等被重定向到了gitee的logo上，而目前的解决方案还不完全，只能暂时在`console - 设置 - 代码注入 > 全局header代码注入`加入代码来实现资源的正常请求，（如下图）：
![image](https://github.com/MartyAlien/plugin-giteeoss/assets/62040646/24e336bf-d480-4288-b10f-b98a30bfa1a9)

```HTML
<!-- 加入下面代码 -->

<meta name="referrer" content="no-referrer">

```
加入上述代码后保存即可，之所说是不完全解决方案，是因为halo官方支持的全局Head代码注入是不包括 `console` 的，所以你在加入上述代码保存之后，你在控制台中查看图片还是会无法正常显示，但是除了控制台以外的地方(比如引用了该图片或附件的文章、页面)是能够正常显示的。

针对这个不完全方案我也是同步了问题给Halo官方，期望Halo能提供接口，来实现真正意义上的全局代码注入。目前 `plugin-giteeoss` 插件能够做到将此段代码注入到 `console` 之外的其他页面上，来减少用户的手动注入代码，但由于方案不完全，同时我也在等待Halo官方的回应，到时候一起做掉，所以在此之前也只能麻烦一下使用本插件的用户自行配置一下了。

带来了不便之处，实在抱歉，后续等待方案敲定再做统一处理。

以下是我对Halo官方提出的issue可以持续关注一下：
```
https://github.com/halo-dev/halo/issues/3999
```

如果你有更好的方案，可以提在这~

> 关于使用本插件的详细教程，后面我有时间会单独出一下，可以在[这里](https://blog.yocloud.top)查看哈~

**Comment by MartyAlien** [comment]
## 补充
这里是详细教程：https://blog.yocloud.top/aio/use-gitee_oss_plugin

**Comment by zhaoshuailongLxw** [comment]
您好博主  这个教程我看了，我发现上传到gitee 上面的图片  在博客主题里面替换头像是可以看到gitee上传的图片（可以显示），但是在文章选择图片又看不到图片（就是不显示），麻烦看一下   谢谢

**Comment by MartyAlien** [comment]
我不太清楚你说的 `博客主题里面替换头像` 这个位置，`文章-编辑器-选择图片`本身也是在`Console`的body中，所以图片不显示也是必然的(因为需要`Console`的Head中也需要添加代码)，你如果想在`Console`看到图片的话，可以尝试下面的步骤：

1. 进入 `Console` 后，按F12或者在网页空白处鼠标右键选择 `检查` 
![image](https://github.com/MartyAlien/plugin-giteeoss/assets/62040646/e572fd15-75d0-4bd8-b410-6459fd1db42d)

2. 鼠标选中`<head>，单击右键，选择 `Edit as HTML`，在<head>`下面一行输入`<meta name="referrer" content="no-referrer">`代码后点击一下空白处即可，就能在控制台中查看上传到 Gitee 的图片了
![image](https://github.com/MartyAlien/plugin-giteeoss/assets/62040646/262de3b2-e3a0-4ef9-9558-9bcd73536eac)

![image](https://github.com/MartyAlien/plugin-giteeoss/assets/62040646/03203ec7-10c9-47a9-a140-8550f24dee3a)

![image](https://github.com/MartyAlien/plugin-giteeoss/assets/62040646/e1238df3-cd15-4800-a2f6-9879bd75eb36)

**Comment by zhaoshuailongLxw** [comment]
好的  谢谢
